#!/usr/bin/env python
import json

import pika
import psycopg2

connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()
sql = """ 
 INSERT INTO device_deviceupdate (device_id, imei, location, true_track, mag_track, ground_speed, altitude, timestamp, dilution, num_sats, log_time)
  VALUES (%s, %s, ST_SetSRID(ST_MakePoint(%s, %s), 4326), %s, %s, %s, %s, %s, %s, %s, %s)
"""

try:
    conn = psycopg2.connect("dbname='geotool' user='django' host='localhost' password='tiapw4gd2u'")
except:
    print("I am unable to connect to the database")
cur = conn.cursor()

imei_map = {}

def callback(ch, method, properties, body):
    print(" [x] Received %r" % body)
    data = json.loads(body.decode())
    print("Imei is %s" % data["imei"])
    if imei_map.get(data["imei"]):
        device_id = imei_map.get(data["imei"])
    else:
        cur.execute("""select id from device_device where imei=%s""", (data["imei"],))
        rows = cur.fetchall()
        device_id = rows[0][0]
        imei_map[data["imei"]] = device_id
    # keys = data.keys()
    # values = [data[column] for column in data.remove("log_time")]
    result = cur.execute(
        sql, (
            device_id, data["imei"], data["latitude"], data["longitude"], data["true_track"],
            data["mag_track"],
            data["ground_speed"], data["altitude"],
            data["timestamp"], data["dilution"], data["num_sats"], data["log_time"],
        )
    )
    print(result)
    updated_rows = cur.rowcount
    print(updated_rows)
    result = conn.commit()
    print(result)


channel.basic_consume(callback,
                      queue='gps_update',
                      no_ack=True)

channel.queue_declare(queue='gps_update')

print(' [*] Waiting for messages. To exit press CTRL+C')
channel.start_consuming()
