#!/usr/bin/env python
import asyncio
import aio_pika
import json
import os

from geotool_db_api.common import create_pool_a
from geotool_db_api.device_api import get_update_firmware_coroutine
from geotool_db_api.device_api import get_device_id
from mqrecv_lib.firmware_update import main_firmware_update

MQ_HOST = os.environ.get("MQ_HOST", "127.0.0.1")
MQ_USER = os.environ.get("MQ_USER", "guest")
MQ_PASS = os.environ.get("MQ_PASS", "guest")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(create_pool_a())
    print("Firmware update processsor has started.")
    loop.run_until_complete(main_firmware_update(loop))
    loop.close()