#!/usr/bin/env python

import asyncio
import os
import logging

from geotool_db_api.common import create_pool_a
from meitrack.file_download import FileDownloadAggregator
from mqrecv_lib.mt_file_fragment import main_mt_file_fragment

logger = logging.getLogger(__name__)
MQ_HOST = os.environ.get("MQ_HOST", "127.0.0.1")
MQ_USER = os.environ.get("MQ_USER", "guest")
MQ_PASS = os.environ.get("MQ_PASS", "guest")


if __name__ == "__main__":
    main_file_agg = FileDownloadAggregator()
    main_loop = asyncio.get_event_loop()
    main_loop.run_until_complete(create_pool_a())
    print("Meitrack file fragment processor has started.")
    main_loop.run_until_complete(main_mt_file_fragment(main_loop, main_file_agg))
    main_loop.close()
