# Docker image for running python applications

FROM simchatserver-base-dev:interim
MAINTAINER Matt Clark <mattjclark0407@hotmail.com>
RUN pip install celery-flower

USER sysadmin
ENTRYPOINT ["/usr/local/bin/celery"]
CMD ["flower", ""-A", "sim_chat_lib.celerytasks.sendcommand", "worker", "-l", "info"]
